# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEa8mtpYYJkarWxDh4pka_JvkGFDfTJD
"""

pip install streamlit

import streamlit as st


st.title("ML Assignment 2")
st.subheader("Implementation of Multiple Classification Models")

